name: winner_casino_test
description: Winner Casino Test project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  go_router: ^3.1.0
  logging: ^1.0.2
  http: ^0.13.4
  toast: ^0.3.0
  intl: ^0.17.0
  socket_io_client: ^1.0.2
  material_design_icons_flutter: ^5.0.6595

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
